# Generated by Django 5.0 on 2023-12-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
